[tool.poetry]
name = "word-jam"
version = "0.1.0"
description = "A crossword game which you can play during your free time"
authors = ["AshBlade <jeenamurali100tab@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.6"
cython = "^0.29.14"
kivy = "^1.11.1"
kivymd = "^0.103.0"

[tool.poetry.dev-dependencies]
pytest = "^4.6"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
